### ISSUE TITLE
Assess our Docker practices against so-called "best practices"

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/workflow.transition.monitor#100]
Bad habits: 

1. Attempting to use VM practices on containers.
2. Creating Docker files that are not transparent.
3. Creating Dockerfiles that have external side effects.
4. Confusing images used for deployment with those used for development.
5. Building different images per environment.
6. Pulling code from git into production servers and building images on the fly.
7. Promoting git hashes between teams.
8. Hardcoding secrets into container images.
9. Using Docker as poor man’s CI/CD.
10. Assuming that containers are a dumb packaging method.

Source: https://codefresh.io/blog/docker-anti-patterns/

**Comment by cjyetman** [comment]
@jdhoffa is this still relevant?

**Comment by jdhoffa** [comment]
I think we have made massive improvements to our Dockerfiles in general (and workflow.pacta is the final step, to not require baking in the data)

But I would ask @AlexAxthelm to have a look at this issue to see what he thinks before closing it? 

(I'm happy to close it)

**Comment by AlexAxthelm** [comment]
General notes about our trends. There's a few outlier dockerfiles that still need to get cleaned, but they're on the todo list.

> * Attempting to use VM practices on containers.

✅ We're much better about treating containers as ephemeral, and not relying on machine state to control application state

> * Creating Docker files that are not transparent.

✅ Not letting `pak` install sysdeps is a big one here

> * Creating Dockerfiles that have external side effects.

✅ We've never done much of this
> * Confusing images used for deployment with those used for development.

⛔ We're generally doing our testing on PROD images. Overall, I don't think this is the low-hanging fruit that we want to chase down next, since minifying R environments is a giant pain.

> * Building different images per environment.

✅ related to previous point, any of our images are theoretically ready to go into PROD.

> * Pulling code from git into production servers and building images on the fly.

✅ We've always had a hard separation between build and deploy. Note that when we start attaching PACTA-data, this might get interesting

> * Promoting git hashes between teams.

✅ pretty good on this one. Having many repos go into a single image makes it such that docker tag as the unit of promotion is simpler.

> * Hardcoding secrets into container images.

✅ We still have a few containers that get secrets baked in (workflow.data.preparation being the notable offender), but those are on their way out. This repo necessarily includes "secrets" (pacta-data) in the image, so its a valid exception

> * Using Docker as poor man’s CI/CD.

✅ Good here. Build steps are just building

> * Assuming that containers are a dumb packaging method.

✅ Good here
