### ISSUE TITLE
Consider if we need to clone all dependent PACTA packages in `build/build_with_tag.sh`

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/workflow.transition.monitor#165]
Or if it is acceptable to use instead `pak::install_pkg`. 
Both seem to effectively do the same thing (either clone a repo to a local directory, and copy it into a Docker image, or clone and build the package directly when building the Docker image). 

The latter seems more transparent to me, and doesn't seem to lose any of the benefits of the former (for example, tracking of the git hash used to build is still possible).

**Comment by cjyetman** [comment]
Since #199 was merged, the build script no longer clones the pacta packages repos locally/manually and copies them into the image to install from there, and instead installs them directly from GitHub (now that they're all packagatized and public) inside the image, and it facilitates installing at any specific branch/tag/sha/pr. (This repo and the templates.transition.monitor repos do still get locally/manually cloned and copied in because they are not R packages, but their head hashes still get recorded.)

Also of note, installing with `pak::pak()` or `pak::install_pkg()` *does* record the sha of the commit that it installs from in the installed package DESCRIPTION, which can be seen for instance with...

``` r
packageDescription("pacta.portfolio.import", fields = "GithubSHA1")
#> [1] "13beda3b52afc6e53ff644b1d454001c596dd79b"

sessioninfo::session_info(pkgs = "pacta.portfolio.import", dependencies = FALSE)$packages$source
#> [1] "Github (RMI-PACTA/pacta.portfolio.import@13beda3b52afc6e53ff644b1d454001c596dd79b)"
```

so the sha does end up in the [`environment_info.json` file that pacta.portfolio.report saves](https://github.com/RMI-PACTA/pacta.portfolio.report/blob/dc98d15314641d1d97fea75d4f16fbf7b08eae46/R/export_environment_info.R#L86-L93).
