### ISSUE TITLE
consider removing `RUN exit 0`

### ISSUE THREAD

**Issue by cjyetman** [RMI-PACTA/workflow.transition.monitor#193]
https://github.com/RMI-PACTA/workflow.transition.monitor/blob/5ba843ca588dcf5acb4ad66cf3579bfdb1474f7e/Dockerfile#L160

This line has been around [since 3 years ago](https://github.com/RMI-PACTA/docker/blame/8df0a0ed68b5a6cdc1da195662cf3881fbb5e324/pacta/Dockerfile) and frankly I don't know what it does or what effect it has. @AlexAxthelm and @jdhoffa should/can we get rid of this?

**Comment by cjyetman** [comment]
now I'm having a vague memory of something.... that the base image that we were using by default would spin up an RStudio web version, and our image would inherit that `RUN` command even though it is non-obvious, and so setting `RUN exit 0` would overwrite that default so one would not inadvertently open the RStudio web app and open ports to it etc.

**Comment by cjyetman** [comment]
Revisiting this because I'm skeptical about it again. If the purpose is to define the behavior of the Docker image after it is built, e.g. when one does `docker run [image_name]` we want the default behavior to exit immediately, wouldn't that have to be done with `CMD exit 0` not `RUN exit 0`? If I understand correctly, `RUN exit 0` will only run once during the build of the Docker image, but not affect the behavior of a Docker container invoked from it, right?

I'm leaning again towards removing this `RUN exit 0`.

**Comment by jdhoffa** [comment]
Honestly, I'm not entirely sure why it is there, I was just reasoning about why it MIGHT be there. 

If you are sure it is totally safe to remove then go ahead!

**Comment by cjyetman** [comment]
I'm not *sure* about anything that relates to this 😂

**Comment by jdhoffa** [comment]
Hahhaha neither am I. All I meant is that I don't KNOW of any reason for it, all I can do is speculate. So if it's bothering you, you can remove it!

But I'm gonna make sure it's YOU that removes it because I don't want to be responsible for the unforeseen consequences 😂

**Comment by jdhoffa** [comment]
And my speculation is well-documented above

**Comment by cjyetman** [comment]
Yeah, I'm leaning conservative here and leaving it in until I figure out what it actually does and if we need it or not.

**Comment by AlexAxthelm** [comment]
I haven't dug in heavily to this dockerfile (most of my focus has been on [`workflow.pacta`](https://github.com/RMI-PACTA/workflow.pacta)), but as near as I can tell the line in question doesn't do anything, and can be removed without consequence.

`RUN` lines are only relevant during the build process, so this is adding a layer to the image that simply runs `exit 0` from a new shell opened from the image defined by the lines above. Since that will always exit cleanly without further action, as it stands this doesn't do anything.

The behavior that @jdhoffa described would be correctly imp[lements with @cjyetman's suggestion of `CMD exit 0`, (or more idomatically, `CMD ["exit", "0"]`, but I would probably suggest that we don't do that if our expected invocation is to always run it with something along the lines of `docker run <imageName> run-r-scripts 1234`. In that case, I'd encourage us to make a simple script that emits a useful error message letting the user know that they haven't overridden the command correctly, and exit with a non-zero code, and have that be the `CMD` we use.

**Comment by jdhoffa** [comment]
Sounds interesting to me!!

Also, are we actually at a stage where we're ready to deprecate this repo in favor of `workflow.pacta`?? Basically, is there another `workflow` repo somewhere that does the interactive report portion of things?

(I have a call with CJ to go over this repo tomorrow, so maybe i just wait for my questions to be answered then)
